<a href="https://colab.research.google.com/github/hanhanwu/Hanhan_COLAB_Experiemnts/blob/master/SVD_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Type 1 Python SVD

* This method allows you to get complete S, U, V

In [0]:
import numpy as np
from numpy.linalg import svd

In [0]:
A = np.array([[1,2,3], [4,5,6], [5,7,9]])

U, S, VT = svd(A)

In [0]:
print("Left Singular Vectors:")
print(U)
print("Singular Values:") 
print(np.diag(S))
print("Right Singular Vectors:") 
print(VT)

Left Singular Vectors:
[[-0.2354116   0.78182354 -0.57735027]
 [-0.55937325 -0.5947842  -0.57735027]
 [-0.79478485  0.18703934  0.57735027]]
Singular Values:
[[1.56633231e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 8.12593979e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.17807579e-15]]
Right Singular Vectors:
[[-0.41158755 -0.56381288 -0.71603821]
 [-0.8148184  -0.12429146  0.56623547]
 [-0.40824829  0.81649658 -0.40824829]]


In [0]:
# Return the original matrix A
# @ is used for matrix multiplication in Py3, use np.matmul with Py2
print(U @ np.diag(S) @ VT)

[[1. 2. 3.]
 [4. 5. 6.]
 [5. 7. 9.]]


## Type 2 Pyhton SVD

* This is ised for dimensional reduction directly